site_name: Argos Sci Docs
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

nav:
  - Index:
    - Welcome: index.md
    - Creating Documentation: index/Creating Documentation.md
    
  - PMS7003:
    - Sensor Connection Guide: pms7003/PMS7003.md
    - Running the Script: pms7003/Running the Script.md
    - Understanding the Data: pms7003/Understanding the Data.md

  - SOP Generaton:
    - Creating SOP Documents: SOP Generaton/SOP GPT.md
    - Outline Questions: SOP Generaton/Outline Questions.md

copyright: "&copy; 2023 <a href='https://argos-sci.com/' target='_blank' rel='noopener'>Argos Scientific, Inc.</a>"

extra_css:
  - stylesheets/extra.css